apiVersion: apps/v1 # versao do codigo
kind: Deployment # recurso a ser criado

metadata: 
  name: hello-gitops # nome da aplicacao

spec:
  replicas: 1 # numero de replicas pods que tem que ficar rodando

  selector: # labels da aplicacao
    matchLabels:
      app: hello-gitops

  template:

    metadata:
      labels:
        app: hello-gitops

    spec:

        containers:

          - name: hello-gitops
            image: jairowmd/hello-gitops:v1

            ports:
            - containerPort: 80
