name: primeiro CI # É apenas o nome da Pipeline.

on:
    push:
      branches:
        - main

jobs: # Pense no Job como um funcionário. Uma Pipeline pode ter vários funcionários trabalhando.

    primeiro-job: # Nome do Job. É apenas um identificador.

        runs-on: ubuntu-latest # O GitHub cria automaticamente uma máquina Ubuntu.
        
        steps:

                - name: Checkout do código
                  uses: actions/checkout@v4

                - name: Mostrar arquivos
                  run: ls -la

                - name: mostrar diretorio atual
                  run: pwd

                - name: Mostrar versao do docker
                  run: docker --version