name: primeiro CI # É apenas o nome da Pipeline.

on:
    workflow_dispatch: # "Não execute automaticamente."

jobs: # Pense no Job como um funcionário. Uma Pipeline pode ter vários funcionários trabalhando.

    deploy: # Nome do Job. É apenas um identificador.

        runs-on: ubuntu-lastest # O GitHub cria automaticamente uma máquina Ubuntu.
        
        steps:

                - name: Checkout do código
                  uses: actions/checkout@v4

                - name: Mostrar arquivos
                  run: ls -la

                - name: Build da imagem
                  run: docker build -t hello-api:v1 .

                - name: Mostrar imagens
                  run: docker images