name: primeiro CI # É apenas o nome da Pipeline.

on:
    push:
      branches:
        - main

jobs: # Pense no Job como um funcionário. Uma Pipeline pode ter vários funcionários trabalhando.

    primeiro-job: # Nome do Job. É apenas um identificador.

        runs-on: ubuntu-latest # O GitHub cria automaticamente uma máquina Ubuntu.
        
        steps:

                - name: Checkout do código
                  uses: actions/checkout@v4

                - name: Gerar tag da imagem
                  id: vars
                  run: |
                    echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

                - name: Mostrar tag
                  run: |
                    echo "Tag gerada: ${{ env.TAG }}"

                - name: Login Docker Hub
                  uses: docker/login-action@v3
                  with:
                    username: ${{secrets.DOCKERHUB_USERNAME}}
                    password: ${{secrets.DOCKERHUB_TOKEN}}

                - name: Build da imagem
                  run: |
                    docker build -t jairowmd/hello-gitops:${{ env.TAG }} .

                - name: Mostrar imagens criadas
                  run: docker images

                - name: Push da imagem
                  run: docker push jairowmd/hello-gitops:${{ env.TAG }}